- name: conditions
  hosts: web
  become: yes
  tasks: 
  - name: checking user present or not
    ansible.builtin.command: id rayudu
    register: USER
    ignore_errors: true
  - name: Create USER
    ansible.builtin.command: useradd {{USER}}
    when: rc != 0
      

