- name: conditions
  hosts: web
  become: yes
  tasks: 
  - name: checking user present or not
    ansible.builtin.command: id rayudu
    register: USER
    ignore_errors: true
  - name: print user information
    ansible.builtin.debug:
      msg: "user info: {{USER}}"
  - name: Create User
    ansible.builtin.command: useradd {{USER}}
    when: USER.rc != 0
      

